### ISSUE TITLE
Smite event doesn't work because the target is always the first string in the message

### ISSUE THREAD

**Issue by Mysteryem** [SirRandoo/toolkit-utils#55]
We were trying to smite someone in a stream today. After figuring out that it's moderator/channel owner only, it told us that "!buy" is not in the colony.

I'm not a c# dev, but the problem line appears to be: https://github.com/SirRandoo/toolkit-utils/blob/5758eb16a88b69bd2d106b919a7b62da4d2784ae/Source/ToolkitUtils/Incidents/Smite.cs#L44

If the `msg` is `"!buy smite <viewer>"` then

1.  `split(' ')` breaks it into an array:
`["!buy", "smite", "<viewer>"]`
1. `Take(2)` returns the first 2 elements from the start:
`["!buy", "smite"]`
1. `FirstOrDefault()` returns the first element:
`"!buy"`

The problem lies at 2., I think you probably intended to use the [`Skip(2)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.skip?view=net-5.0) method to skip the first two elements of the split message, rather than taking the first two elements with [`Take(2)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.take?view=net-5.0).

**Comment by SirRandoo** [comment]
Just following up to this to say that the fix was pushed to Steam. If you have anymore problems with the mod, feel free to leave a bug report here, the workshop page, or the discord. 😃
