### ISSUE TITLE
Wear charging viewers twice

### ISSUE THREAD

**Issue by Mysteryem** [SirRandoo/toolkit-utils#59]
Someone pointed out today that they were spending more coins than the item's cost when using `wear` to buy and wear clothing. After looking at the numbers and accounting for their coin gain over time, the amount of coins they spent was exactly double the item's cost.

It looks like the viewer is being charged twice in Wear.cs, first at https://github.com/SirRandoo/toolkit-utils/blob/935ae474f0e814a97eaf9cd19bdd8eae8b9476b3/Source/ToolkitUtils/Incidents/Wear.cs#L130 and then immediately again in the FinalizeTransaction call https://github.com/SirRandoo/toolkit-utils/blob/935ae474f0e814a97eaf9cd19bdd8eae8b9476b3/Source/ToolkitUtils/Incidents/Wear.cs#L147

**Comment by SirRandoo** [comment]
Thanks! A fix has been pushed to Steam, and should be fixed once the update downloads.
