### ISSUE TITLE
Is this out of date? Tons of errors when using this with 1.5 

### ISSUE THREAD

**Issue by 3liza-git** [SirRandoo/toolkit-utils#84]
When enabling this mod with all current DLC on 1.5, ToolkitCore and Twitch Toolkit I get a ton of errors in the log and the game itself breaks. UI acts weird, either not appearing or not going away when another button is clicked, and the base game menu is inaccessible which requires a force quit or alt-f4 to get out of. Error log: https://pastebin.com/NjU0YvNe

**Comment by 3liza-git** [comment]
No other mods enabled except the ones listed above and Harmony.

**Comment by SirRandoo** [comment]
The Steam version of the mod hasn't been updated to 1.5. For the latest 1.5 release, you'd have to download the latest beta version of the mod from its [releases](https://github.com/sirrandoo/toolkit-utils/releases) page.

Once you've done that you'd need to unzip the file into your game's "mods" directory under a folder named whatever, but it's typically named "ToolkitUtils."

**Comment by 3liza-git** [comment]
Thanks, I installed the beta version and don't see a login/twitch credentials window. Was that removed?

**Comment by SirRandoo** [comment]
The credentials window is provided by ToolkitCore, which is released alongside [Twitch Toolkit](https://github.com/harleyknd1/twitchtoolkit/releases).
